# Generated by Django 5.2.16 on 2026-08-10 11:01

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('project_code', models.CharField(max_length=100, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=250, verbose_name='项目名称')),
                ('short_name', models.CharField(blank=True, max_length=150, verbose_name='项目简称')),
                ('status', models.CharField(choices=[('PLANNING', '筹备'), ('ACTIVE', '进行中'), ('PAUSED', '暂停'), ('COMPLETED', '已完成'), ('ARCHIVED', '已归档')], default='PLANNING', max_length=16, verbose_name='项目状态')),
                ('visibility', models.CharField(choices=[('INTERNAL', '课题组内部可见'), ('RESTRICTED', '受限项目')], default='INTERNAL', max_length=16, verbose_name='可见性')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='项目说明')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='principal_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ('-created_at', 'project_code'),
                'permissions': [('archive_project', 'Can formally archive projects'), ('transfer_project_pi', 'Can transfer project principal investigator'), ('soft_delete_project', 'Can soft delete projects')],
            },
        ),
        migrations.CreateModel(
            name='ProjectAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消或撤销'), ('EXPIRED', '已到期')], default='PENDING', max_length=16, verbose_name='申请状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核说明')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='访问到期时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='projects.project', verbose_name='项目')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_project_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '项目访问申请',
                'verbose_name_plural': '项目访问申请',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PI', '项目负责人'), ('MANAGER', '项目管理员'), ('MEMBER', '项目成员'), ('VIEWER', '只读成员')], max_length=16, verbose_name='项目角色')),
                ('access_source', models.CharField(choices=[('DIRECT', '直接分配'), ('APPROVED_REQUEST', '访问申请获批')], default='DIRECT', max_length=24, verbose_name='授权来源')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='projects.project', verbose_name='项目')),
                ('source_access_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='granted_membership', to='projects.projectaccessrequest', verbose_name='来源访问申请')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'ordering': ('project', 'role', 'joined_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型代码')),
                ('name', models.CharField(max_length=150, verbose_name='类型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '项目类型',
                'verbose_name_plural': '项目类型',
                'ordering': ('sort_order', 'name', 'code'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True)), name='projects_unique_active_type_name_ci'), models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='projects_project_type_code_not_empty'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='projects_project_type_name_not_empty')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projecttype', verbose_name='项目类型'),
        ),
        migrations.AddConstraint(
            model_name='projectaccessrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('project', 'requester'), name='projects_unique_pending_access_request'),
        ),
        migrations.AddConstraint(
            model_name='projectaccessrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED'])), name='projects_access_request_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectaccessrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='projects_access_request_reason_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='projectaccessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('review_note', ''), _negated=True), _connector='OR'), name='projects_rejected_request_has_note'),
        ),
        migrations.AddConstraint(
            model_name='projectaccessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'PENDING')), models.Q(('status', 'PENDING'), _negated=True), _connector='OR'), name='projects_pending_request_unreviewed'),
        ),
        migrations.AddConstraint(
            model_name='projectaccessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('APPROVED', 'REJECTED')), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='projects_reviewed_request_has_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('project', 'user'), name='projects_unique_active_membership'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True), ('role', 'PI')), fields=('project',), name='projects_unique_active_pi'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['PI', 'MANAGER', 'MEMBER', 'VIEWER'])), name='projects_membership_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(('access_source__in', ['DIRECT', 'APPROVED_REQUEST'])), name='projects_membership_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_source', 'DIRECT'), ('expires_at__isnull', True), ('source_access_request__isnull', True)), models.Q(('access_source', 'APPROVED_REQUEST'), ('role', 'VIEWER'), ('source_access_request__isnull', False)), _connector='OR'), name='projects_membership_grant_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='projects_membership_left_after_joined'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('joined_at')), _connector='OR'), name='projects_membership_expires_after_joined'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PLANNING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED'])), name='projects_project_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['INTERNAL', 'RESTRICTED'])), name='projects_project_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='projects_project_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('project_code', ''), _negated=True), name='projects_project_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='projects_project_name_not_empty'),
        ),
    ]
