# Generated by Django 5.2.16 on 2026-08-10 07:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username_fingerprint", models.CharField(max_length=64)),
                ("source_ip", models.GenericIPAddressField()),
                ("failure_count", models.PositiveSmallIntegerField(default=0)),
                ("window_started_at", models.DateTimeField()),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "登录限制",
                "verbose_name_plural": "登录限制",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.CharField(blank=True, max_length=200, verbose_name="院系或部门"),
                ),
                (
                    "student_or_staff_id",
                    models.CharField(blank=True, max_length=100, verbose_name="学工号"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="联系电话"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="管理员备注")),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("username",),
                "permissions": [
                    ("reset_user_password", "Can reset user passwords"),
                    ("change_user_status", "Can change user lifecycle status"),
                    ("assign_system_roles", "Can assign predefined system roles"),
                ],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "正常"),
                    ("DISABLED", "临时禁用"),
                    ("DEPARTED", "已离组"),
                    ("ARCHIVED", "已归档"),
                ],
                default="ACTIVE",
                max_length=16,
                verbose_name="账号状态",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False, verbose_name="必须修改密码"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account_status", "ACTIVE"), ("is_active", True)),
                    models.Q(
                        models.Q(("account_status", "ACTIVE"), _negated=True),
                        ("is_active", False),
                    ),
                    _connector="OR",
                ),
                name="accounts_user_status_matches_is_active",
            ),
        ),
        migrations.AddIndex(
            model_name="loginthrottle",
            index=models.Index(
                fields=["locked_until", "updated_at"],
                name="accounts_lo_locked__e24772_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="loginthrottle",
            constraint=models.UniqueConstraint(
                fields=("username_fingerprint", "source_ip"),
                name="accounts_unique_login_throttle_key",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="accounts.user",
            ),
        ),
    ]
