# Generated by Django 5.2.16 on 2026-08-19

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


CATEGORY_SCOPE_SQL = """
CREATE FUNCTION documents_enforce_document_category_scope()
RETURNS trigger AS $$
DECLARE
    category_project uuid;
    category_active boolean;
BEGIN
    SELECT project_id, is_active
      INTO category_project, category_active
      FROM documents_documentcategory
     WHERE id = NEW.category_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Document category does not exist.' USING ERRCODE = '23503';
    END IF;
    IF NOT category_active THEN
        RAISE EXCEPTION 'Inactive document category cannot be assigned.'
            USING ERRCODE = '23514';
    END IF;
    IF category_project IS NOT NULL AND category_project <> NEW.project_id THEN
        RAISE EXCEPTION 'Document category belongs to another project.'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER documents_document_category_scope_trigger
AFTER INSERT OR UPDATE OF project_id, category_id ON documents_document
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION documents_enforce_document_category_scope();

CREATE FUNCTION documents_prevent_category_scope_change()
RETURNS trigger AS $$
BEGIN
    IF NEW.project_id IS DISTINCT FROM OLD.project_id THEN
        RAISE EXCEPTION 'Document category scope is immutable.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER documents_category_scope_immutable_trigger
BEFORE UPDATE OF project_id ON documents_documentcategory
FOR EACH ROW EXECUTE FUNCTION documents_prevent_category_scope_change();
"""

CATEGORY_SCOPE_REVERSE_SQL = """
DROP TRIGGER IF EXISTS documents_category_scope_immutable_trigger
    ON documents_documentcategory;
DROP FUNCTION IF EXISTS documents_prevent_category_scope_change();
DROP TRIGGER IF EXISTS documents_document_category_scope_trigger
    ON documents_document;
DROP FUNCTION IF EXISTS documents_enforce_document_category_scope();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, verbose_name="分类代码")),
                ("name", models.CharField(max_length=150, verbose_name="分类名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_categories",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档分类",
                "verbose_name_plural": "文档分类",
                "ordering": ("sort_order", "name", "code"),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("code"),
                        condition=models.Q(("project__isnull", True)),
                        name="documents_unique_global_category_code_ci",
                    ),
                    models.UniqueConstraint(
                        models.F("project"),
                        django.db.models.functions.text.Lower("code"),
                        condition=models.Q(("project__isnull", False)),
                        name="documents_unique_project_category_code_ci",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("project__isnull", True)),
                        name="documents_unique_global_category_name_ci",
                    ),
                    models.UniqueConstraint(
                        models.F("project"),
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("project__isnull", False)),
                        name="documents_unique_project_category_name_ci",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("code", ""), _negated=True),
                        name="documents_category_code_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="documents_category_name_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "stored_filename",
                    models.CharField(max_length=255, unique=True, verbose_name="存储文件名"),
                ),
                (
                    "relative_path",
                    models.CharField(max_length=500, unique=True, verbose_name="相对存储路径"),
                ),
                (
                    "declared_mime_type",
                    models.CharField(blank=True, max_length=255, verbose_name="客户端声明 MIME"),
                ),
                (
                    "detected_mime_type",
                    models.CharField(blank=True, max_length=255, verbose_name="服务端检测 MIME"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(blank=True, null=True, verbose_name="文件大小"),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="SHA256"
                    ),
                ),
                (
                    "storage_status",
                    models.CharField(
                        choices=[
                            ("TEMPORARY", "临时"),
                            ("QUARANTINED", "已隔离"),
                            ("AVAILABLE", "可用"),
                            ("MISSING", "物理文件缺失或完整性异常"),
                            ("DELETED", "已软删除"),
                        ],
                        default="TEMPORARY",
                        max_length=16,
                        verbose_name="存储状态",
                    ),
                ),
                (
                    "malware_scan_status",
                    models.CharField(
                        choices=[
                            ("NOT_CONFIGURED", "未配置"),
                            ("PENDING", "待扫描"),
                            ("CLEAN", "扫描通过"),
                            ("INFECTED", "检测到威胁"),
                            ("ERROR", "扫描失败"),
                        ],
                        default="NOT_CONFIGURED",
                        max_length=20,
                        verbose_name="恶意软件扫描状态",
                    ),
                ),
                (
                    "status_reason",
                    models.CharField(blank=True, max_length=100, verbose_name="状态原因代码"),
                ),
                (
                    "upload_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="上传幂等令牌",
                    ),
                ),
                (
                    "quarantined_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="隔离时间"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_file_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件资产",
                "verbose_name_plural": "文件资产",
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "storage_status__in",
                                ["TEMPORARY", "QUARANTINED", "AVAILABLE", "MISSING", "DELETED"],
                            )
                        ),
                        name="documents_file_storage_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "malware_scan_status__in",
                                ["NOT_CONFIGURED", "PENDING", "CLEAN", "INFECTED", "ERROR"],
                            )
                        ),
                        name="documents_malware_scan_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("original_filename", ""), _negated=True),
                        name="documents_original_filename_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stored_filename", ""), _negated=True),
                        name="documents_stored_filename_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("relative_path", ""), _negated=True),
                        name="documents_relative_path_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("relative_path__startswith", "/"), _negated=True),
                            models.Q(("relative_path__contains", "\\"), _negated=True),
                            models.Q(("relative_path__contains", ".."), _negated=True),
                            models.Q(("relative_path__regex", "^[A-Za-z]:"), _negated=True),
                            models.Q(("stored_filename__contains", "/"), _negated=True),
                            models.Q(("stored_filename__contains", "\\"), _negated=True),
                        ),
                        name="documents_storage_keys_safe_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("file_size__isnull", True), ("file_size__gt", 0), _connector="OR"
                        ),
                        name="documents_file_size_positive_when_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sha256", ""), ("sha256__regex", "^[0-9a-f]{64}$"), _connector="OR"
                        ),
                        name="documents_sha256_blank_or_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("storage_status__in", ("AVAILABLE", "MISSING", "DELETED")),
                                _negated=True,
                            ),
                            models.Q(
                                ("file_size__gt", 0),
                                models.Q(("sha256", ""), _negated=True),
                                models.Q(("detected_mime_type", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="documents_final_asset_metadata_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("storage_status", "QUARANTINED"), _negated=True),
                            ("quarantined_at__isnull", False),
                            _connector="OR",
                        ),
                        name="documents_quarantined_asset_has_time",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("storage_status", "AVAILABLE"), _negated=True),
                            ("malware_scan_status__in", ("NOT_CONFIGURED", "CLEAN")),
                            _connector="OR",
                        ),
                        name="documents_available_scan_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("deleted_at__isnull", False), ("storage_status", "DELETED")),
                            models.Q(
                                models.Q(("storage_status", "DELETED"), _negated=True),
                                ("deleted_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="documents_deleted_asset_has_time",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "document_group_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="文档组"),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="版本")),
                ("is_current", models.BooleanField(default=True, verbose_name="当前版本")),
                ("is_final", models.BooleanField(default=False, verbose_name="最终版")),
                ("title", models.CharField(max_length=250, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("document_date", models.DateField(blank=True, null=True, verbose_name="文档日期")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="documents.documentcategory",
                        verbose_name="文档分类",
                    ),
                ),
                (
                    "file_asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document",
                        to="documents.fileasset",
                        verbose_name="文件资产",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目文档",
                "verbose_name_plural": "项目文档",
                "ordering": ("-created_at", "title"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_group_id", "version"),
                        name="documents_unique_group_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True), ("is_current", True)),
                        fields=("document_group_id",),
                        name="documents_unique_active_current_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="documents_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="documents_title_not_empty",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=CATEGORY_SCOPE_SQL,
            reverse_sql=CATEGORY_SCOPE_REVERSE_SQL,
        ),
    ]
