# Generated by Django 5.2.16 on 2026-08-10 07:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "登录成功"),
                            ("LOGIN_FAILED", "登录失败"),
                            ("LOGOUT", "退出登录"),
                            ("PASSWORD_CHANGED", "用户修改密码"),
                            ("PASSWORD_RESET_BY_ADMIN", "管理员重置密码"),
                            ("USER_CREATED", "创建用户"),
                            ("USER_STATUS_CHANGED", "修改账号状态"),
                            ("ROLE_ASSIGNED", "分配角色"),
                            ("ROLE_REMOVED", "移除角色"),
                            ("PROFILE_UPDATED", "更新个人资料"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=150)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "request_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "成功"),
                            ("DENIED", "拒绝"),
                            ("FAILED", "失败"),
                        ],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id", "created_at"],
                        name="audit_audit_object__81040e_idx",
                    )
                ],
            },
        ),
    ]
