# Generated by Django 5.2.16 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "登录成功"),
                    ("LOGIN_FAILED", "登录失败"),
                    ("LOGOUT", "退出登录"),
                    ("PASSWORD_CHANGED", "用户修改密码"),
                    ("PASSWORD_RESET_BY_ADMIN", "管理员重置密码"),
                    ("USER_CREATED", "创建用户"),
                    ("USER_STATUS_CHANGED", "修改账号状态"),
                    ("ROLE_ASSIGNED", "分配角色"),
                    ("ROLE_REMOVED", "移除角色"),
                    ("PROFILE_UPDATED", "更新个人资料"),
                    ("PROJECT_CREATED", "创建项目"),
                    ("PROJECT_UPDATED", "更新项目"),
                    ("PROJECT_ARCHIVED", "归档项目"),
                    ("PROJECT_SOFT_DELETED", "软删除项目"),
                    ("PROJECT_MEMBER_ADDED", "添加项目成员"),
                    ("PROJECT_MEMBER_UPDATED", "更新项目成员"),
                    ("PROJECT_MEMBER_REMOVED", "移除项目成员"),
                    ("PROJECT_PI_TRANSFERRED", "更换项目负责人"),
                    ("ACCESS_REQUEST_SUBMITTED", "提交项目访问申请"),
                    ("ACCESS_REQUEST_APPROVED", "批准项目访问申请"),
                    ("ACCESS_REQUEST_REJECTED", "拒绝项目访问申请"),
                    ("ACCESS_REQUEST_CANCELLED", "取消项目访问申请"),
                    ("ACCESS_REQUEST_REVOKED", "撤销项目访问授权"),
                    ("ACCESS_REQUEST_EXPIRED", "项目访问授权到期"),
                    ("FILE_UPLOADED", "文件上传完成"),
                    ("FILE_UPLOAD_FAILED", "文件上传失败"),
                    ("FILE_DOWNLOADED", "文件下载"),
                    ("FILE_QUARANTINED", "文件隔离"),
                    ("FILE_MARKED_MISSING", "文件标记缺失"),
                    ("FILE_INTEGRITY_FAILED", "文件完整性校验失败"),
                    ("DOCUMENT_SOFT_DELETED", "文档软删除"),
                    ("DOCUMENT_RESTORED", "文档恢复"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
