LAB_MEMBER_GROUP = "LAB_MEMBER"
REIMBURSEMENT_ADMIN_GROUP = "REIMBURSEMENT_ADMIN"
SYSTEM_ADMIN_GROUP = "SYSTEM_ADMIN"

SYSTEM_GROUP_NAMES = (
    LAB_MEMBER_GROUP,
    REIMBURSEMENT_ADMIN_GROUP,
    SYSTEM_ADMIN_GROUP,
)
